#!/bin/sh

if [ -z "$1" ]; then
        echo "Missing argument (commit message). Did you try to run this manually?"
        exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
        echo "Commit hook: ignoring branch merge"
        exit 0
fi

# check semantic versioning schemes
if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
        echo "Your commit title did not follow semantic versioning: $commitTitle"
        echo "Must conform to feat|fix|docs|style|refactor|perf|test|chore(subject/jira): short_desc"
        echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
        exit 1
fi